credentials:
  usernames:
    admin:
      name: 'bmw'
      password: '213'  # كلمة سر تجريبية
    user1:
      name: 'Trading User'
      password: '456'
cookie:
  expiry_days: 30
  key: 'some_random_key'
  name: 'auth_cookie'